"""
Write docs/company/org_chart.md: Arcadia's leadership org chart at the latest month-end.

Reads marts.mart_org_leader_summary from the warehouse built by run_pipeline.py and
draws the CEO, the eight function heads, the sub-function heads and every department
head as a Mermaid chart (GitHub renders it), followed by a table with each leader's
direct and total reports. People and names are fictional.

    python pipeline/run_pipeline.py --no-export
    python pipeline/build_org_chart.py
"""

from __future__ import annotations

from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "warehouse" / "arcadia.duckdb"
OUT = ROOT / "docs" / "company" / "org_chart.md"


def node_id(org_unit_id: str) -> str:
    return org_unit_id.replace("-", "_")


def main(con: duckdb.DuckDBPyConnection | None = None):
    con = con or duckdb.connect(str(DB_PATH), read_only=True)
    as_of = con.execute("SELECT MAX(month_end_date) FROM marts.mart_org_leader_summary").fetchone()[0]
    rows = con.execute("""
        SELECT org_unit_type, org_unit_id, org_unit_name, parent_org_unit_id, function_name, leader_title,
               worker_name, grade, office_name, direct_reports, total_reports
        FROM marts.mart_org_leader_summary
        WHERE month_end_date = ?
        ORDER BY CASE org_unit_type WHEN 'Company' THEN 1 WHEN 'Function' THEN 2 WHEN 'Sub-function' THEN 3 ELSE 4 END,
                 total_reports DESC
    """, [as_of]).fetchall()
    cols = ["type", "id", "name", "parent", "function", "title", "leader", "grade", "office", "direct", "total"]
    units = [dict(zip(cols, r)) for r in rows]
    headcount = units[0]["total"] + 1

    lines = [
        "# Arcadia Systems: leadership org chart",
        "",
        f"As of **{as_of:%Y-%m-%d}** (end of FY{as_of.year % 100}): **{headcount:,} people**, every one of them in a single",
        "reporting line that ends at the CEO. Each box shows the leader, their level and two counts:",
        "**direct** reports and **total** people in their organization (direct plus everyone below them).",
        "",
        "> Arcadia Systems is fictional and all names are invented. Generated by",
        "> [`pipeline/build_org_chart.py`](../../pipeline/build_org_chart.py) from `mart_org_leader_summary`.",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    for u in units:
        if u["type"] == "Company":
            label = f'<b>{u["leader"]}</b><br/>Chief Executive Officer<br/>{u["direct"]} direct · {u["total"]:,} total'
        elif u["type"] == "Function":
            label = f'<b>{u["name"]}</b><br/>{u["leader"]}, {u["title"]}<br/>{u["direct"]} direct · {u["total"]:,} total'
        elif u["type"] == "Sub-function":
            label = f'<b>{u["name"]}</b><br/>{u["leader"]}, SVP<br/>{u["direct"]} direct · {u["total"]:,} total'
        else:
            label = f'<b>{u["name"]}</b><br/>{u["leader"]}, L{u["grade"]}<br/>{u["direct"]} direct · {u["total"]:,} total'
        lines.append(f'    {node_id(u["id"])}["{label}"]')
    for u in units:
        if u["parent"]:
            lines.append(f'    {node_id(u["parent"])} --> {node_id(u["id"])}')
    lines += [
        "    classDef company fill:#0F2A44,color:#FFFFFF,stroke:#0F2A44",
        "    classDef function fill:#1F5C99,color:#FFFFFF,stroke:#1F5C99",
        "    classDef sub fill:#DCE8F5,color:#0F2A44,stroke:#1F5C99",
        "    classDef dept fill:#FFFFFF,color:#0F2A44,stroke:#9DB4CC",
        f'    class {node_id(units[0]["id"])} company',
        "    class " + ",".join(node_id(u["id"]) for u in units if u["type"] == "Function") + " function",
        "    class " + ",".join(node_id(u["id"]) for u in units if u["type"] == "Sub-function") + " sub",
        "    class " + ",".join(node_id(u["id"]) for u in units if u["type"] == "Department") + " dept",
        "```",
        "",
        "## Leaders",
        "",
        "| Unit | Type | Leader | Role | Level | Office | Direct | Total |",
        "|---|---|---|---|---:|---|---:|---:|",
    ]
    for u in units:
        lines.append(f'| {u["name"]} | {u["type"]} | {u["leader"]} | {u["title"]} | L{u["grade"]} | {u["office"]} '
                     f'| {u["direct"]:,} | {u["total"]:,} |')
    lines += [
        "",
        "Direct reports of a department head include their directors and managers and, in smaller departments,",
        "individual contributors. A total counts everyone below a leader, so a function head's total equals the",
        "totals of its department heads plus the department and sub-function heads themselves.",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(units)} leaders, as of {as_of})")


if __name__ == "__main__":
    main()
