/*
  02_load_raw.sql  (generated by sqlserver/make_load_raw.py; do not edit by hand)
  Lands every CSV from data/raw/ into the raw schema as text, the way an
  enterprise landing zone receives files. Types are applied later in 03.

  The repository folder is mounted into the container at /repo (see the setup
  guide), so SQL Server reads the files directly with BULK INSERT.
*/
SET NOCOUNT ON;
USE ArcadiaHR;
GO

DROP TABLE IF EXISTS raw.dim_country;
CREATE TABLE raw.dim_country (
    [country_code]  NVARCHAR(400) NULL,
    [country_name]  NVARCHAR(400) NULL,
    [region]        NVARCHAR(400) NULL,
    [currency_code] NVARCHAR(400) NULL,
    [pay_index]     NVARCHAR(400) NULL
);
BULK INSERT raw.dim_country
FROM '/repo/data/raw/dim_country.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_dim_country INT = (SELECT COUNT(*) FROM raw.dim_country);
PRINT CONCAT('raw.dim_country', '                     ', @n_dim_country, ' rows');
GO

DROP TABLE IF EXISTS raw.dim_department;
CREATE TABLE raw.dim_department (
    [department_id]       NVARCHAR(400) NULL,
    [department_name]     NVARCHAR(400) NULL,
    [sub_function]        NVARCHAR(400) NULL,
    [function]            NVARCHAR(400) NULL,
    [parent_org_unit_id]  NVARCHAR(400) NULL,
    [cost_center]         NVARCHAR(400) NULL,
    [head_job_level]      NVARCHAR(400) NULL,
    [effective_from_date] NVARCHAR(400) NULL
);
BULK INSERT raw.dim_department
FROM '/repo/data/raw/dim_department.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_dim_department INT = (SELECT COUNT(*) FROM raw.dim_department);
PRINT CONCAT('raw.dim_department', '                  ', @n_dim_department, ' rows');
GO

DROP TABLE IF EXISTS raw.dim_job_level;
CREATE TABLE raw.dim_job_level (
    [job_level]          NVARCHAR(400) NULL,
    [level_code]         NVARCHAR(400) NULL,
    [level_name]         NVARCHAR(400) NULL,
    [career_track]       NVARCHAR(400) NULL,
    [us_base_salary_usd] NVARCHAR(400) NULL,
    [range_min_pct]      NVARCHAR(400) NULL,
    [range_max_pct]      NVARCHAR(400) NULL
);
BULK INSERT raw.dim_job_level
FROM '/repo/data/raw/dim_job_level.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_dim_job_level INT = (SELECT COUNT(*) FROM raw.dim_job_level);
PRINT CONCAT('raw.dim_job_level', '                   ', @n_dim_job_level, ' rows');
GO

DROP TABLE IF EXISTS raw.dim_job_profile;
CREATE TABLE raw.dim_job_profile (
    [job_profile_id]  NVARCHAR(400) NULL,
    [job_family_code] NVARCHAR(400) NULL,
    [job_family]      NVARCHAR(400) NULL,
    [job_title]       NVARCHAR(400) NULL,
    [job_level]       NVARCHAR(400) NULL,
    [level_name]      NVARCHAR(400) NULL,
    [career_track]    NVARCHAR(400) NULL
);
BULK INSERT raw.dim_job_profile
FROM '/repo/data/sqlserver/dim_job_profile.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_dim_job_profile INT = (SELECT COUNT(*) FROM raw.dim_job_profile);
PRINT CONCAT('raw.dim_job_profile', '                 ', @n_dim_job_profile, ' rows');
GO

DROP TABLE IF EXISTS raw.dim_location;
CREATE TABLE raw.dim_location (
    [location_id]     NVARCHAR(400) NULL,
    [office_name]     NVARCHAR(400) NULL,
    [site_type]       NVARCHAR(400) NULL,
    [street_address]  NVARCHAR(400) NULL,
    [city]            NVARCHAR(400) NULL,
    [state_province]  NVARCHAR(400) NULL,
    [postal_code]     NVARCHAR(400) NULL,
    [country_code]    NVARCHAR(400) NULL,
    [country_name]    NVARCHAR(400) NULL,
    [region]          NVARCHAR(400) NULL,
    [currency_code]   NVARCHAR(400) NULL,
    [latitude]        NVARCHAR(400) NULL,
    [longitude]       NVARCHAR(400) NULL,
    [geo_source]      NVARCHAR(400) NULL,
    [pay_zone_factor] NVARCHAR(400) NULL,
    [opened_date]     NVARCHAR(400) NULL
);
BULK INSERT raw.dim_location
FROM '/repo/data/sqlserver/dim_location.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_dim_location INT = (SELECT COUNT(*) FROM raw.dim_location);
PRINT CONCAT('raw.dim_location', '                    ', @n_dim_location, ' rows');
GO

DROP TABLE IF EXISTS raw.dim_org_unit;
CREATE TABLE raw.dim_org_unit (
    [org_unit_id]        NVARCHAR(400) NULL,
    [org_unit_name]      NVARCHAR(400) NULL,
    [org_unit_type]      NVARCHAR(400) NULL,
    [parent_org_unit_id] NVARCHAR(400) NULL,
    [function]           NVARCHAR(400) NULL,
    [leader_title]       NVARCHAR(400) NULL,
    [leader_job_level]   NVARCHAR(400) NULL
);
BULK INSERT raw.dim_org_unit
FROM '/repo/data/sqlserver/dim_org_unit.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_dim_org_unit INT = (SELECT COUNT(*) FROM raw.dim_org_unit);
PRINT CONCAT('raw.dim_org_unit', '                    ', @n_dim_org_unit, ' rows');
GO

DROP TABLE IF EXISTS raw.dim_worker;
CREATE TABLE raw.dim_worker (
    [worker_id]            NVARCHAR(400) NULL,
    [first_name]           NVARCHAR(400) NULL,
    [last_name]            NVARCHAR(400) NULL,
    [original_hire_date]   NVARCHAR(400) NULL,
    [termination_date]     NVARCHAR(400) NULL,
    [termination_type]     NVARCHAR(400) NULL,
    [worker_type]          NVARCHAR(400) NULL,
    [is_executive_officer] NVARCHAR(400) NULL
);
BULK INSERT raw.dim_worker
FROM '/repo/data/raw/dim_worker.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_dim_worker INT = (SELECT COUNT(*) FROM raw.dim_worker);
PRINT CONCAT('raw.dim_worker', '                      ', @n_dim_worker, ' rows');
GO

DROP TABLE IF EXISTS raw.fact_bonus_payout;
CREATE TABLE raw.fact_bonus_payout (
    [bonus_id]                 NVARCHAR(400) NULL,
    [worker_id]                NVARCHAR(400) NULL,
    [fiscal_year]              NVARCHAR(400) NULL,
    [payout_date]              NVARCHAR(400) NULL,
    [currency_code]            NVARCHAR(400) NULL,
    [base_salary_annual_local] NVARCHAR(400) NULL,
    [fte]                      NVARCHAR(400) NULL,
    [proration_factor]         NVARCHAR(400) NULL,
    [bonus_pct]                NVARCHAR(400) NULL,
    [bonus_amount_local]       NVARCHAR(400) NULL,
    [payout_status]            NVARCHAR(400) NULL
);
BULK INSERT raw.fact_bonus_payout
FROM '/repo/data/raw/fact_bonus_payout.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_fact_bonus_payout INT = (SELECT COUNT(*) FROM raw.fact_bonus_payout);
PRINT CONCAT('raw.fact_bonus_payout', '               ', @n_fact_bonus_payout, ' rows');
GO

DROP TABLE IF EXISTS raw.fact_compensation_history;
CREATE TABLE raw.fact_compensation_history (
    [comp_record_id]           NVARCHAR(400) NULL,
    [worker_id]                NVARCHAR(400) NULL,
    [effective_start_date]     NVARCHAR(400) NULL,
    [effective_end_date]       NVARCHAR(400) NULL,
    [action_reason]            NVARCHAR(400) NULL,
    [transaction_type]         NVARCHAR(400) NULL,
    [currency_code]            NVARCHAR(400) NULL,
    [base_salary_annual_local] NVARCHAR(400) NULL
);
BULK INSERT raw.fact_compensation_history
FROM '/repo/data/raw/fact_compensation_history.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_fact_compensation_history INT = (SELECT COUNT(*) FROM raw.fact_compensation_history);
PRINT CONCAT('raw.fact_compensation_history', '       ', @n_fact_compensation_history, ' rows');
GO

DROP TABLE IF EXISTS raw.fact_job_history;
CREATE TABLE raw.fact_job_history (
    [job_record_id]        NVARCHAR(400) NULL,
    [worker_id]            NVARCHAR(400) NULL,
    [effective_start_date] NVARCHAR(400) NULL,
    [effective_end_date]   NVARCHAR(400) NULL,
    [action_reason]        NVARCHAR(400) NULL,
    [position_id]          NVARCHAR(400) NULL,
    [department_id]        NVARCHAR(400) NULL,
    [location_id]          NVARCHAR(400) NULL,
    [job_profile_id]       NVARCHAR(400) NULL,
    [job_level]            NVARCHAR(400) NULL,
    [fte]                  NVARCHAR(400) NULL,
    [manager_worker_id]    NVARCHAR(400) NULL,
    [is_people_manager]    NVARCHAR(400) NULL,
    [leads_org_unit_id]    NVARCHAR(400) NULL
);
BULK INSERT raw.fact_job_history
FROM '/repo/data/raw/fact_job_history.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_fact_job_history INT = (SELECT COUNT(*) FROM raw.fact_job_history);
PRINT CONCAT('raw.fact_job_history', '                ', @n_fact_job_history, ' rows');
GO

DROP TABLE IF EXISTS raw.fact_performance_review;
CREATE TABLE raw.fact_performance_review (
    [review_id]   NVARCHAR(400) NULL,
    [worker_id]   NVARCHAR(400) NULL,
    [fiscal_year] NVARCHAR(400) NULL,
    [review_date] NVARCHAR(400) NULL,
    [rating]      NVARCHAR(400) NULL,
    [bonus_pct]   NVARCHAR(400) NULL
);
BULK INSERT raw.fact_performance_review
FROM '/repo/data/raw/fact_performance_review.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_fact_performance_review INT = (SELECT COUNT(*) FROM raw.fact_performance_review);
PRINT CONCAT('raw.fact_performance_review', '         ', @n_fact_performance_review, ' rows');
GO

DROP TABLE IF EXISTS raw.ref_fringe_rate;
CREATE TABLE raw.ref_fringe_rate (
    [country_code]              NVARCHAR(400) NULL,
    [year]                      NVARCHAR(400) NULL,
    [effective_start_date]      NVARCHAR(400) NULL,
    [effective_end_date]        NVARCHAR(400) NULL,
    [social_contribution_rate]  NVARCHAR(400) NULL,
    [retirement_severance_rate] NVARCHAR(400) NULL,
    [statutory_pay_rate]        NVARCHAR(400) NULL,
    [employer_benefits_rate]    NVARCHAR(400) NULL,
    [fringe_rate]               NVARCHAR(400) NULL,
    [reference_salary_local]    NVARCHAR(400) NULL,
    [is_estimate]               NVARCHAR(400) NULL,
    [method_note]               NVARCHAR(400) NULL
);
BULK INSERT raw.ref_fringe_rate
FROM '/repo/data/sqlserver/ref_fringe_rate.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_ref_fringe_rate INT = (SELECT COUNT(*) FROM raw.ref_fringe_rate);
PRINT CONCAT('raw.ref_fringe_rate', '                 ', @n_ref_fringe_rate, ' rows');
GO

DROP TABLE IF EXISTS raw.ref_fringe_source;
CREATE TABLE raw.ref_fringe_source (
    [country_code] NVARCHAR(400) NULL,
    [year]         NVARCHAR(400) NULL,
    [component]    NVARCHAR(400) NULL,
    [source_id]    NVARCHAR(400) NULL,
    [source_title] NVARCHAR(400) NULL,
    [source_url]   NVARCHAR(400) NULL
);
BULK INSERT raw.ref_fringe_source
FROM '/repo/data/sqlserver/ref_fringe_source.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_ref_fringe_source INT = (SELECT COUNT(*) FROM raw.ref_fringe_source);
PRINT CONCAT('raw.ref_fringe_source', '               ', @n_ref_fringe_source, ' rows');
GO

DROP TABLE IF EXISTS raw.ref_fx_rate_constant;
CREATE TABLE raw.ref_fx_rate_constant (
    [rate_set]      NVARCHAR(400) NULL,
    [rate_date]     NVARCHAR(400) NULL,
    [currency_code] NVARCHAR(400) NULL,
    [usd_per_local] NVARCHAR(400) NULL
);
BULK INSERT raw.ref_fx_rate_constant
FROM '/repo/data/raw/ref_fx_rate_constant.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_ref_fx_rate_constant INT = (SELECT COUNT(*) FROM raw.ref_fx_rate_constant);
PRINT CONCAT('raw.ref_fx_rate_constant', '            ', @n_ref_fx_rate_constant, ' rows');
GO

DROP TABLE IF EXISTS raw.ref_fx_rate_daily;
CREATE TABLE raw.ref_fx_rate_daily (
    [currency_code] NVARCHAR(400) NULL,
    [rate_date]     NVARCHAR(400) NULL,
    [usd_per_local] NVARCHAR(400) NULL,
    [source]        NVARCHAR(400) NULL
);
BULK INSERT raw.ref_fx_rate_daily
FROM '/repo/data/sqlserver/ref_fx_rate_daily.psv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = '|', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_ref_fx_rate_daily INT = (SELECT COUNT(*) FROM raw.ref_fx_rate_daily);
PRINT CONCAT('raw.ref_fx_rate_daily', '               ', @n_ref_fx_rate_daily, ' rows');
GO

DROP TABLE IF EXISTS raw.ref_fx_rate_monthly;
CREATE TABLE raw.ref_fx_rate_monthly (
    [currency_code] NVARCHAR(400) NULL,
    [rate_date]     NVARCHAR(400) NULL,
    [usd_per_local] NVARCHAR(400) NULL
);
BULK INSERT raw.ref_fx_rate_monthly
FROM '/repo/data/raw/ref_fx_rate_monthly.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_ref_fx_rate_monthly INT = (SELECT COUNT(*) FROM raw.ref_fx_rate_monthly);
PRINT CONCAT('raw.ref_fx_rate_monthly', '             ', @n_ref_fx_rate_monthly, ' rows');
GO

DROP TABLE IF EXISTS raw.ref_job_level_base_salary;
CREATE TABLE raw.ref_job_level_base_salary (
    [job_level]                    NVARCHAR(400) NULL,
    [country_code]                 NVARCHAR(400) NULL,
    [currency_code]                NVARCHAR(400) NULL,
    [base_salary_local]            NVARCHAR(400) NULL,
    [base_salary_usd_at_reference] NVARCHAR(400) NULL,
    [fx_reference_date]            NVARCHAR(400) NULL
);
BULK INSERT raw.ref_job_level_base_salary
FROM '/repo/data/raw/ref_job_level_base_salary.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_ref_job_level_base_salary INT = (SELECT COUNT(*) FROM raw.ref_job_level_base_salary);
PRINT CONCAT('raw.ref_job_level_base_salary', '       ', @n_ref_job_level_base_salary, ' rows');
GO

DROP TABLE IF EXISTS raw.ref_performance_bonus;
CREATE TABLE raw.ref_performance_bonus (
    [rating]       NVARCHAR(400) NULL,
    [bonus_pct]    NVARCHAR(400) NULL,
    [target_share] NVARCHAR(400) NULL
);
BULK INSERT raw.ref_performance_bonus
FROM '/repo/data/raw/ref_performance_bonus.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_ref_performance_bonus INT = (SELECT COUNT(*) FROM raw.ref_performance_bonus);
PRINT CONCAT('raw.ref_performance_bonus', '           ', @n_ref_performance_bonus, ' rows');
GO

DROP TABLE IF EXISTS raw.ref_salary_range;
CREATE TABLE raw.ref_salary_range (
    [fiscal_year]   NVARCHAR(400) NULL,
    [job_level]     NVARCHAR(400) NULL,
    [country_code]  NVARCHAR(400) NULL,
    [currency_code] NVARCHAR(400) NULL,
    [range_min]     NVARCHAR(400) NULL,
    [range_mid]     NVARCHAR(400) NULL,
    [range_max]     NVARCHAR(400) NULL
);
BULK INSERT raw.ref_salary_range
FROM '/repo/data/raw/ref_salary_range.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_ref_salary_range INT = (SELECT COUNT(*) FROM raw.ref_salary_range);
PRINT CONCAT('raw.ref_salary_range', '                ', @n_ref_salary_range, ' rows');
GO

DROP TABLE IF EXISTS raw.ref_tenure_increase;
CREATE TABLE raw.ref_tenure_increase (
    [tenure_year_from] NVARCHAR(400) NULL,
    [tenure_year_to]   NVARCHAR(400) NULL,
    [increase_pct]     NVARCHAR(400) NULL
);
BULK INSERT raw.ref_tenure_increase
FROM '/repo/data/raw/ref_tenure_increase.csv'
WITH (FIRSTROW = 2, FIELDTERMINATOR = ',', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_ref_tenure_increase INT = (SELECT COUNT(*) FROM raw.ref_tenure_increase);
PRINT CONCAT('raw.ref_tenure_increase', '             ', @n_ref_tenure_increase, ' rows');
GO
