"""
Write sqlserver/02_load_raw.sql from the headers of the CSVs in data/raw/.

Every raw table lands as NVARCHAR text, like a landing zone, so the load script is
pure boilerplate; generating it keeps it in step with the generator's output.

    python sqlserver/make_load_raw.py
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
OUT = ROOT / "sqlserver" / "02_load_raw.sql"

HEADER = """/*
  02_load_raw.sql  (generated by sqlserver/make_load_raw.py; do not edit by hand)
  Lands every CSV from data/raw/ into the raw schema as text, the way an
  enterprise landing zone receives files. Types are applied later in 03.

  The repository folder is mounted into the container at /repo (see the setup
  guide), so SQL Server reads the files directly with BULK INSERT.
*/
SET NOCOUNT ON;
USE ArcadiaHR;
GO
"""


def block(table: str, columns: list[str]) -> str:
    width = max(len(c) for c in columns) + 2
    cols = ",\n".join(f"    [{c}]{' ' * (width - len(c) - 2)} NVARCHAR(400) NULL" for c in columns)
    pad = " " * max(1, 36 - len(f"raw.{table}"))
    return f"""
DROP TABLE IF EXISTS raw.{table};
CREATE TABLE raw.{table} (
{cols}
);
BULK INSERT raw.{table}
FROM '/repo/data/raw/{table}.csv'
WITH (FORMAT = 'CSV', FIRSTROW = 2, FIELDQUOTE = '"', ROWTERMINATOR = '0x0a', TABLOCK);
DECLARE @n_{table} INT = (SELECT COUNT(*) FROM raw.{table});
PRINT CONCAT('raw.{table}', '{pad}', @n_{table}, ' rows');
GO
"""


def main():
    parts = [HEADER]
    for path in sorted(RAW.glob("*.csv")):
        with path.open(newline="") as f:
            columns = next(csv.reader(f))
        parts.append(block(path.stem, columns))
    OUT.write_text("".join(parts))
    print(f"Wrote {OUT.relative_to(ROOT)} for {len(parts) - 1} raw tables")


if __name__ == "__main__":
    main()
